const CONSTANTS = {
  REGISTER: 'REGISTER',
  LOGIN: 'LOGIN',
  ESTABLISH_SESSION: 'ESTABLISH_SESSION',
  CLOSE_SESSION: 'CLOSE_SESSION',
  CLEAN_IMAGE_SIGNUP: 'CLEAN_IMAGE_SIGNUP',
  LOAD_IMAGE_SIGNUP: 'LOAD_IMAGE_SIGNUP',
};

export default CONSTANTS;
